# Generated by Django 5.1.3 on 2024-12-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0002_remove_appuser_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff'), ('client', 'Client'), ('hairdresser', 'Hairdresser')], default='client', help_text='Designates the role of the user.', max_length=20),
        ),
    ]
