# Generated by Django 5.1.3 on 2024-12-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0002_remove_appointment_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.CharField(help_text='YYYY-MM-DD'),
        ),
    ]
