# Generated by Django 5.1.2 on 2024-12-10 20:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'ordering': ['time_slots__date'],
            },
        ),
        migrations.CreateModel(
            name='AvailableDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='An available date for selection.', unique=True)),
            ],
            options={
                'verbose_name': 'Available Date',
                'verbose_name_plural': 'Available Dates',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], help_text='The recurring day of the week this schedule applies to. Leave blank for a specific date.', max_length=10, unique=True)),
                ('start_time', models.TimeField(help_text='Start time of the working hours.')),
                ('end_time', models.TimeField(help_text='End time of the working hours.')),
                ('slot_duration', models.DurationField(default=datetime.timedelta(seconds=1800), help_text='Duration of each appointment slot.')),
                ('max_bookings_per_slot', models.PositiveIntegerField(default=1, help_text='Maximum bookings allowed for each time slot.')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(help_text='The start time of the time slot.')),
                ('is_available', models.BooleanField(default=True, help_text='Whether this slot is available for booking.')),
            ],
            options={
                'verbose_name': 'Time Slot',
                'verbose_name_plural': 'Time Slots',
            },
        ),
    ]
