# Generated by Django 5.1.3 on 2024-12-04 18:27

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='An available date for selection.', unique=True)),
            ],
            options={
                'verbose_name': 'Available Date',
                'verbose_name_plural': 'Available Dates',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='DeactivateTimeSlots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Start date for the period to deactivate time slots.')),
                ('end_date', models.DateField(help_text='End date for the period to deactivate time slots.')),
                ('reason', models.TextField(blank=True, help_text='Optional reason for deactivating the time slots.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Indicates whether the deactivation is still active or not.')),
            ],
            options={
                'verbose_name_plural': 'Deactivate Time Slots',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], help_text='The recurring day of the week this schedule applies to. Leave blank for a specific date.', max_length=10, null=True)),
                ('start_time', models.TimeField(help_text='Start time of the working hours.')),
                ('end_time', models.TimeField(help_text='End time of the working hours.')),
                ('slot_duration', models.DurationField(default=datetime.timedelta(seconds=1800), help_text='Duration of each appointment slot.')),
                ('max_bookings_per_slot', models.PositiveIntegerField(default=1, help_text='Maximum bookings allowed for each time slot.')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates whether the schedule is currently active.')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='The date of the time slot.')),
                ('start_time', models.TimeField(help_text='The start time of the time slot.')),
                ('is_available', models.BooleanField(default=True, help_text='Whether this slot is available for booking.')),
                ('schedule', models.ForeignKey(help_text='The schedule this time slot belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='hairDressersApp.schedule')),
            ],
            options={
                'verbose_name': 'Time Slot',
                'verbose_name_plural': 'Time Slots',
                'unique_together': {('date', 'start_time', 'schedule')},
            },
        ),
    ]
