# Generated by Django 5.1.2 on 2024-12-10 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('hairDressersApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='common.service'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='hairDressersApp.availabledate'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='date',
            field=models.ForeignKey(help_text='The date of the time slot.', on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='hairDressersApp.availabledate'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='time_slots',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='hairDressersApp.timeslot'),
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('date', 'start_time')},
        ),
    ]
