# Generated by Django 5.1.3 on 2024-12-01 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairDressersApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indicates whether the schedule is currently active.'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='specific_date',
            field=models.DateField(blank=True, help_text='Specific date for this schedule. Overrides the weekly schedule for that date.', null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='day_of_week',
            field=models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], help_text='The recurring day of the week this schedule applies to. Leave blank for a specific date.', max_length=10, null=True),
        ),
    ]
