# Generated by Django 5.1.3 on 2024-12-09 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairDressersApp', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='day_of_week',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], help_text='The recurring day of the week this schedule applies to. Leave blank for a specific date.', max_length=10, unique=True),
        ),
    ]
