# Generated by Django 5.1.3 on 2024-12-06 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hairDressersApp', '0002_appointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeactivateTimeSlots',
        ),
    ]
